// <auto-generated />
using System;
using DYBus.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace DYBus.Migrations
{
    [DbContext(typeof(BusDbContent))]
    [Migration("20181011120135_Init")]
    partial class Init
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.4-rtm-31024")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("DYBus.Models.BusRunTimeInfo", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("AheadStationNo");

                    b.Property<string>("BeforeStationNo");

                    b.Property<string>("BusCarNo");

                    b.Property<string>("BusRunDirection");

                    b.Property<string>("BusStatus");

                    b.Property<DateTime>("CreateTime");

                    b.Property<string>("IsAtFinalStop");

                    b.Property<string>("RoadNum");

                    b.HasKey("Id");

                    b.ToTable("BusRunTimeInfos");
                });
#pragma warning restore 612, 618
        }
    }
}
